package com.bs.glr.mapper;

import com.bs.glr.bean.BsToken;
import com.bs.glr.bean.BsTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    long countByExample(BsTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    int deleteByExample(BsTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    int insert(BsToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    int insertSelective(BsToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    List<BsToken> selectByExample(BsTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    BsToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") BsToken record, @Param("example") BsTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    int updateByExample(@Param("record") BsToken record, @Param("example") BsTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    int updateByPrimaryKeySelective(BsToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    int updateByPrimaryKey(BsToken record);
}