package com.bs.glr.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class BsBookInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public BsBookInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBNameIsNull() {
            addCriterion("b_name is null");
            return (Criteria) this;
        }

        public Criteria andBNameIsNotNull() {
            addCriterion("b_name is not null");
            return (Criteria) this;
        }

        public Criteria andBNameEqualTo(String value) {
            addCriterion("b_name =", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameNotEqualTo(String value) {
            addCriterion("b_name <>", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameGreaterThan(String value) {
            addCriterion("b_name >", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameGreaterThanOrEqualTo(String value) {
            addCriterion("b_name >=", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameLessThan(String value) {
            addCriterion("b_name <", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameLessThanOrEqualTo(String value) {
            addCriterion("b_name <=", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameLike(String value) {
            addCriterion("b_name like", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameNotLike(String value) {
            addCriterion("b_name not like", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameIn(List<String> values) {
            addCriterion("b_name in", values, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameNotIn(List<String> values) {
            addCriterion("b_name not in", values, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameBetween(String value1, String value2) {
            addCriterion("b_name between", value1, value2, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameNotBetween(String value1, String value2) {
            addCriterion("b_name not between", value1, value2, "bName");
            return (Criteria) this;
        }

        public Criteria andBMsgIsNull() {
            addCriterion("b_msg is null");
            return (Criteria) this;
        }

        public Criteria andBMsgIsNotNull() {
            addCriterion("b_msg is not null");
            return (Criteria) this;
        }

        public Criteria andBMsgEqualTo(String value) {
            addCriterion("b_msg =", value, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgNotEqualTo(String value) {
            addCriterion("b_msg <>", value, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgGreaterThan(String value) {
            addCriterion("b_msg >", value, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgGreaterThanOrEqualTo(String value) {
            addCriterion("b_msg >=", value, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgLessThan(String value) {
            addCriterion("b_msg <", value, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgLessThanOrEqualTo(String value) {
            addCriterion("b_msg <=", value, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgLike(String value) {
            addCriterion("b_msg like", value, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgNotLike(String value) {
            addCriterion("b_msg not like", value, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgIn(List<String> values) {
            addCriterion("b_msg in", values, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgNotIn(List<String> values) {
            addCriterion("b_msg not in", values, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgBetween(String value1, String value2) {
            addCriterion("b_msg between", value1, value2, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBMsgNotBetween(String value1, String value2) {
            addCriterion("b_msg not between", value1, value2, "bMsg");
            return (Criteria) this;
        }

        public Criteria andBPriceIsNull() {
            addCriterion("b_price is null");
            return (Criteria) this;
        }

        public Criteria andBPriceIsNotNull() {
            addCriterion("b_price is not null");
            return (Criteria) this;
        }

        public Criteria andBPriceEqualTo(BigDecimal value) {
            addCriterion("b_price =", value, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceNotEqualTo(BigDecimal value) {
            addCriterion("b_price <>", value, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceGreaterThan(BigDecimal value) {
            addCriterion("b_price >", value, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("b_price >=", value, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceLessThan(BigDecimal value) {
            addCriterion("b_price <", value, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("b_price <=", value, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceIn(List<BigDecimal> values) {
            addCriterion("b_price in", values, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceNotIn(List<BigDecimal> values) {
            addCriterion("b_price not in", values, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("b_price between", value1, value2, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("b_price not between", value1, value2, "bPrice");
            return (Criteria) this;
        }

        public Criteria andBNumberIsNull() {
            addCriterion("b_number is null");
            return (Criteria) this;
        }

        public Criteria andBNumberIsNotNull() {
            addCriterion("b_number is not null");
            return (Criteria) this;
        }

        public Criteria andBNumberEqualTo(Integer value) {
            addCriterion("b_number =", value, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberNotEqualTo(Integer value) {
            addCriterion("b_number <>", value, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberGreaterThan(Integer value) {
            addCriterion("b_number >", value, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("b_number >=", value, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberLessThan(Integer value) {
            addCriterion("b_number <", value, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberLessThanOrEqualTo(Integer value) {
            addCriterion("b_number <=", value, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberIn(List<Integer> values) {
            addCriterion("b_number in", values, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberNotIn(List<Integer> values) {
            addCriterion("b_number not in", values, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberBetween(Integer value1, Integer value2) {
            addCriterion("b_number between", value1, value2, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("b_number not between", value1, value2, "bNumber");
            return (Criteria) this;
        }

        public Criteria andBRfidIsNull() {
            addCriterion("b_rfid is null");
            return (Criteria) this;
        }

        public Criteria andBRfidIsNotNull() {
            addCriterion("b_rfid is not null");
            return (Criteria) this;
        }

        public Criteria andBRfidEqualTo(String value) {
            addCriterion("b_rfid =", value, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidNotEqualTo(String value) {
            addCriterion("b_rfid <>", value, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidGreaterThan(String value) {
            addCriterion("b_rfid >", value, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidGreaterThanOrEqualTo(String value) {
            addCriterion("b_rfid >=", value, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidLessThan(String value) {
            addCriterion("b_rfid <", value, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidLessThanOrEqualTo(String value) {
            addCriterion("b_rfid <=", value, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidLike(String value) {
            addCriterion("b_rfid like", value, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidNotLike(String value) {
            addCriterion("b_rfid not like", value, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidIn(List<String> values) {
            addCriterion("b_rfid in", values, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidNotIn(List<String> values) {
            addCriterion("b_rfid not in", values, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidBetween(String value1, String value2) {
            addCriterion("b_rfid between", value1, value2, "bRfid");
            return (Criteria) this;
        }

        public Criteria andBRfidNotBetween(String value1, String value2) {
            addCriterion("b_rfid not between", value1, value2, "bRfid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_book_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 31 22:47:47 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_book_info
     *
     * @mbg.generated Thu Mar 31 22:47:47 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}