package com.bs.glr.bean;

public class BsRfid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_rfid.id
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_rfid.rfid_id
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    private String rfidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_rfid.rfid_status
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    private String rfidStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_rfid.id
     *
     * @return the value of bs_rfid.id
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_rfid.id
     *
     * @param id the value for bs_rfid.id
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_rfid.rfid_id
     *
     * @return the value of bs_rfid.rfid_id
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public String getRfidId() {
        return rfidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_rfid.rfid_id
     *
     * @param rfidId the value for bs_rfid.rfid_id
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public void setRfidId(String rfidId) {
        this.rfidId = rfidId == null ? null : rfidId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_rfid.rfid_status
     *
     * @return the value of bs_rfid.rfid_status
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public String getRfidStatus() {
        return rfidStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_rfid.rfid_status
     *
     * @param rfidStatus the value for bs_rfid.rfid_status
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public void setRfidStatus(String rfidStatus) {
        this.rfidStatus = rfidStatus == null ? null : rfidStatus.trim();
    }
}