package com.bs.glr.bean;

import java.util.ArrayList;
import java.util.List;

public class BsRfidExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public BsRfidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRfidIdIsNull() {
            addCriterion("rfid_id is null");
            return (Criteria) this;
        }

        public Criteria andRfidIdIsNotNull() {
            addCriterion("rfid_id is not null");
            return (Criteria) this;
        }

        public Criteria andRfidIdEqualTo(String value) {
            addCriterion("rfid_id =", value, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdNotEqualTo(String value) {
            addCriterion("rfid_id <>", value, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdGreaterThan(String value) {
            addCriterion("rfid_id >", value, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdGreaterThanOrEqualTo(String value) {
            addCriterion("rfid_id >=", value, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdLessThan(String value) {
            addCriterion("rfid_id <", value, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdLessThanOrEqualTo(String value) {
            addCriterion("rfid_id <=", value, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdLike(String value) {
            addCriterion("rfid_id like", value, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdNotLike(String value) {
            addCriterion("rfid_id not like", value, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdIn(List<String> values) {
            addCriterion("rfid_id in", values, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdNotIn(List<String> values) {
            addCriterion("rfid_id not in", values, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdBetween(String value1, String value2) {
            addCriterion("rfid_id between", value1, value2, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidIdNotBetween(String value1, String value2) {
            addCriterion("rfid_id not between", value1, value2, "rfidId");
            return (Criteria) this;
        }

        public Criteria andRfidStatusIsNull() {
            addCriterion("rfid_status is null");
            return (Criteria) this;
        }

        public Criteria andRfidStatusIsNotNull() {
            addCriterion("rfid_status is not null");
            return (Criteria) this;
        }

        public Criteria andRfidStatusEqualTo(String value) {
            addCriterion("rfid_status =", value, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusNotEqualTo(String value) {
            addCriterion("rfid_status <>", value, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusGreaterThan(String value) {
            addCriterion("rfid_status >", value, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusGreaterThanOrEqualTo(String value) {
            addCriterion("rfid_status >=", value, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusLessThan(String value) {
            addCriterion("rfid_status <", value, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusLessThanOrEqualTo(String value) {
            addCriterion("rfid_status <=", value, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusLike(String value) {
            addCriterion("rfid_status like", value, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusNotLike(String value) {
            addCriterion("rfid_status not like", value, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusIn(List<String> values) {
            addCriterion("rfid_status in", values, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusNotIn(List<String> values) {
            addCriterion("rfid_status not in", values, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusBetween(String value1, String value2) {
            addCriterion("rfid_status between", value1, value2, "rfidStatus");
            return (Criteria) this;
        }

        public Criteria andRfidStatusNotBetween(String value1, String value2) {
            addCriterion("rfid_status not between", value1, value2, "rfidStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_rfid
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 28 18:07:26 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_rfid
     *
     * @mbg.generated Mon Feb 28 18:07:26 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}