package com.bs.glr.bean;

public class BsToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_token.id
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_token.uid
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_token.token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_token.id
     *
     * @return the value of bs_token.id
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_token.id
     *
     * @param id the value for bs_token.id
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_token.uid
     *
     * @return the value of bs_token.uid
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_token.uid
     *
     * @param uid the value for bs_token.uid
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_token.token
     *
     * @return the value of bs_token.token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_token.token
     *
     * @param token the value for bs_token.token
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 2022
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}